# Reference from here : 
# https://wenyuangg.github.io/posts/opencv/opencv-installation.html

From nvcr.io/nvidia/tensorrt:20.09-py3
RUN sed -i -e 's/archive.ubuntu.com/free.nchc.org.tw/' /etc/apt/sources.list

# CUDA 10.2
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y \
    ca-certificates wget sudo protobuf-compiler \
    libprotobuf-dev python3-pip curl vim zip && \
    rm -rf /var/lib/apt/lists/*

RUN /usr/bin/python3 -m pip install --upgrade pip

## Install zsh
RUN ["apt-get", "update"]
RUN ["apt-get", "install", "-y", "zsh"]
RUN wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh || true


### Maybe need to install cmake by apt-get?
RUN apt-get update && apt-get install -y libopencv-dev
RUN apt-get update && apt-get install -y build-essential cmake git libgtk2.0-dev pkg-config
RUN apt-get install -y libavcodec-dev libavformat-dev libswscale-dev python3-dev python3-numpy \
 libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff5-dev
RUN apt-get install -y libdc1394-22-dev libeigen3-dev libtheora-dev libvorbis-dev libxvidcore-dev libx264-dev sphinx-common libtbb-dev yasm libfaac-dev libopencore-amrnb-dev libopencore-amrwb-dev libopenexr-dev libgstreamer-plugins-base1.0-dev libavutil-dev libavfilter-dev libavresample-dev

WORKDIR /opt
RUN git clone https://github.com/Itseez/opencv.git && git clone https://github.com/Itseez/opencv_contrib.git

RUN cd opencv && mkdir release && cd release && mkdir my_build_dir && cd my_build_dir \
 && cmake -D BUILD_TIFF=ON -D WITH_CUDA=OFF -D ENABLE_AVX=OFF -D WITH_OPENGL=OFF -D WITH_OPENCL=OFF -D WITH_IPP=OFF -D WITH_TBB=ON -D BUILD_TBB=ON -D WITH_EIGEN=OFF -D WITH_V4L=OFF -D WITH_VTK=OFF -D BUILD_TESTS=OFF -D BUILD_PERF_TESTS=OFF -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D OPENCV_EXTRA_MODULES_PATH=/opt/opencv_contrib/modules /opt/opencv/ \
 &&  make -j4  &&  make install  && ldconfig

WORKDIR /workspace